### Site Settings ###
title: "code for change. with vedant."
description: >
  i like training deep neural networks
  to solve problems. and sometimes i even
  make websites.
baseurl: ""  # Leave empty if hosted at <your-username>.github.io
repository: "vedsmehta/vedsmehta.github.io"
remote_theme: "YoussefRaafatNasry/portfolYOU"
open_new_tab: false  # Opens external URLs in new tab for posts/projects/navbar


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name: "Vedant Mehta"
  image: "https://i.ibb.co/93d22TXj/IMG-4352-2.jpg"
  email: "veds.mehta@gmail.com"
  github: "vedsmehta"
  instagram: "@vedsmehta"


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Disqus ###
disqus:
  shortname: ""  # Replace with your actual Disqus shortname if using


### Analytics ###
analytics:
  enabled: false
  google:
    tracking_id: ""  # Replace with actual ID if using


### Buy me a coffee ###
buymeacoffee:
  enabled: false
  username: ""
  color: "#007bff"
  message: "Thank you for visiting."
  description: "Support me on Buy me a coffee!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"

  - scope:
      path: ""
      type: "posts"
    values:
      comments: false


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"